### PR TITLE
Allow the nnf-mfu release to be specified.

### PR DESCRIPTION
**Pull request by roehrich-hpe**

### CODE REVIEW

**Comment by roehrich-hpe** [comment]
Here's the NNFContainerProfile example resource that is installed as a result of this change:
```
$ kubectl get nnfcontainerprofiles -n nnf-system example-mpi -o yaml | grep image:
              image: ghcr.io/nearnodeflash/nnf-mfu:0.0.1
            - image: ghcr.io/nearnodeflash/nnf-mfu:0.0.1
```

**Comment by bdevcich-hpe** [comment]
Do you plan on doing this for nnf-dm as well? It's also used there for data movement. https://github.com/search?q=repo%3ANearNodeFlash%2Fnnf-dm%20mfu&type=code

**Comment by roehrich-hpe** [comment]
> Do you plan on doing this for nnf-dm as well? It's also used there for data movement. https://github.com/search?q=repo%3ANearNodeFlash%2Fnnf-dm%20mfu&type=code

Well.  Shoot.

**Comment by roehrich-hpe** [comment]
Here are the results with the newest nnf-dm, from PR https://github.com/NearNodeFlash/nnf-dm/pull/106
```
$ kubectl get datamovementmanager -n nnf-dm-system   nnf-dm-manager-controller-manager -o yaml | grep -e image: -e name:
  name: nnf-dm-manager-controller-manager
        image: ghcr.io/nearnodeflash/nnf-mfu:0.0.1
        name: worker
        - name: NNF_NODE_NAME
        image: ghcr.io/nearnodeflash/nnf-dm:d6b3864f6026ba2a219c7d6d481f35df26cca031
        name: manager

$ docker inspect --format='{{json .Config.Labels}}' ghcr.io/nearnodeflash/nnf-dm:d6b3864f6026ba2a219c7d6d481f35df26cca031
{"nnf-mfu":"ghcr.io/nearnodeflash/nnf-mfu:0.0.1"}


$ kubectl get nnfcontainerprofiles -n nnf-system example-mpi -o yaml | grep image:                                       
              image: ghcr.io/nearnodeflash/nnf-mfu:0.0.1
            - image: ghcr.io/nearnodeflash/nnf-mfu:0.0.1
```

**Review by bdevcich-hpe — APPROVED** [review]

**Review by matthew-richerson — APPROVED** [review]

**Pull request merged**
